package com.slugterra.model.velocity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGrenukeVel extends ModelBase
{
  //fields
    ModelRenderer Face;
    ModelRenderer Body1;
    ModelRenderer Body2;
    ModelRenderer Body3;
    ModelRenderer Body4;
    ModelRenderer Body5;
    ModelRenderer Body6;
    ModelRenderer Body8;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Belly1;
    ModelRenderer Belly2;
    ModelRenderer Shoulder1a;
    ModelRenderer Shoulder1b;
    ModelRenderer Shoulder2b;
    ModelRenderer Shoulder2a;
    ModelRenderer Shoulder3b;
    ModelRenderer Shoulder3a;
    ModelRenderer Shoulder4b;
    ModelRenderer Shoulder4a;
    ModelRenderer Arm1;
    ModelRenderer Arm2;
    ModelRenderer Arm11;
    ModelRenderer Arm12;
    ModelRenderer Arm21;
    ModelRenderer Arm22;
    ModelRenderer Finger13;
    ModelRenderer Finger23;
    ModelRenderer Finger12;
    ModelRenderer Finger11;
    ModelRenderer Finger21;
    ModelRenderer Finger22;
    ModelRenderer Grenade1;
    ModelRenderer Grenade2;
    ModelRenderer Grenade3;
    ModelRenderer Greanade4;
    ModelRenderer Grenade5;
    ModelRenderer Grenade6;
    ModelRenderer Grenade7;
    ModelRenderer Body7;
  
  public ModelGrenukeVel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Face = new ModelRenderer(this, 0, 0);
      Face.addBox(0F, 0F, 0F, 7, 6, 1);
      Face.setRotationPoint(0F, 0F, 0F);
      Face.setTextureSize(64, 64);
      Face.mirror = true;
      setRotation(Face, 0F, 0F, 0F);
      Body1 = new ModelRenderer(this, 0, 8);
      Body1.addBox(0F, 0F, 0F, 9, 6, 1);
      Body1.setRotationPoint(-1F, -1F, 1F);
      Body1.setTextureSize(64, 64);
      Body1.mirror = true;
      setRotation(Body1, 0F, 0F, 0F);
      Body2 = new ModelRenderer(this, 0, 16);
      Body2.addBox(0F, 0F, 0F, 9, 7, 1);
      Body2.setRotationPoint(-1F, -2F, 2F);
      Body2.setTextureSize(64, 64);
      Body2.mirror = true;
      setRotation(Body2, 0F, 0F, 0F);
      Body3 = new ModelRenderer(this, 0, 25);
      Body3.addBox(0F, 0F, 0F, 9, 8, 4);
      Body3.setRotationPoint(-1F, -3F, 3F);
      Body3.setTextureSize(64, 64);
      Body3.mirror = true;
      setRotation(Body3, 0F, 0F, 0F);
      Body4 = new ModelRenderer(this, 0, 38);
      Body4.addBox(0F, 0F, 0F, 9, 7, 1);
      Body4.setRotationPoint(-1F, -2F, 7F);
      Body4.setTextureSize(64, 64);
      Body4.mirror = true;
      setRotation(Body4, 0F, 0F, 0F);
      Body5 = new ModelRenderer(this, 0, 47);
      Body5.addBox(0F, 0F, 0F, 9, 6, 1);
      Body5.setRotationPoint(-1F, -1F, 8F);
      Body5.setTextureSize(64, 64);
      Body5.mirror = true;
      setRotation(Body5, 0F, 0F, 0F);
      Body6 = new ModelRenderer(this, 0, 55);
      Body6.addBox(0F, 0F, 0F, 9, 5, 1);
      Body6.setRotationPoint(-1F, 0F, 9F);
      Body6.setTextureSize(64, 64);
      Body6.mirror = true;
      setRotation(Body6, 0F, 0F, 0F);
      Body8 = new ModelRenderer(this, 21, 60);
      Body8.addBox(0F, 0F, 0F, 7, 3, 1);
      Body8.setRotationPoint(0F, 2F, 11F);
      Body8.setTextureSize(64, 64);
      Body8.mirror = true;
      setRotation(Body8, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 23, 0);
      Tail1.addBox(0F, 0F, 0F, 3, 1, 10);
      Tail1.setRotationPoint(2F, 3F, 11F);
      Tail1.setTextureSize(64, 64);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 23, 0);
      Tail2.addBox(0F, 0F, 0F, 1, 3, 10);
      Tail2.setRotationPoint(3F, 2F, 12F);
      Tail2.setTextureSize(64, 64);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, 0F, 0F);
      Belly1 = new ModelRenderer(this, 23, 0);
      Belly1.addBox(0F, 0F, 0F, 7, 1, 9);
      Belly1.setRotationPoint(0F, 5F, 1F);
      Belly1.setTextureSize(64, 64);
      Belly1.mirror = true;
      setRotation(Belly1, 0F, 0F, 0F);
      Belly2 = new ModelRenderer(this, 23, 0);
      Belly2.addBox(0F, 0F, 0F, 5, 1, 8);
      Belly2.setRotationPoint(1F, 6F, 1F);
      Belly2.setTextureSize(64, 64);
      Belly2.mirror = true;
      setRotation(Belly2, 0F, 0F, 0F);
      Shoulder1a = new ModelRenderer(this, 26, 40);
      Shoulder1a.addBox(0F, 0F, 0F, 1, 5, 1);
      Shoulder1a.setRotationPoint(8F, -1F, 2F);
      Shoulder1a.setTextureSize(64, 64);
      Shoulder1a.mirror = true;
      setRotation(Shoulder1a, 0F, 0F, 0F);
      Shoulder1b = new ModelRenderer(this, 26, 47);
      Shoulder1b.addBox(0F, 0F, 0F, 1, 5, 1);
      Shoulder1b.setRotationPoint(-2F, -1F, 2F);
      Shoulder1b.setTextureSize(64, 64);
      Shoulder1b.mirror = true;
      setRotation(Shoulder1b, 0F, 0F, 0F);
      Shoulder2b = new ModelRenderer(this, 31, 40);
      Shoulder2b.addBox(0F, 0F, 0F, 1, 6, 4);
      Shoulder2b.setRotationPoint(-2F, -2F, 3F);
      Shoulder2b.setTextureSize(64, 64);
      Shoulder2b.mirror = true;
      setRotation(Shoulder2b, 0F, 0F, 0F);
      Shoulder2a = new ModelRenderer(this, 42, 40);
      Shoulder2a.addBox(0F, 0F, 0F, 1, 6, 4);
      Shoulder2a.setRotationPoint(8F, -2F, 3F);
      Shoulder2a.setTextureSize(64, 64);
      Shoulder2a.mirror = true;
      setRotation(Shoulder2a, 0F, 0F, 0F);
      Shoulder3b = new ModelRenderer(this, 36, 28);
      Shoulder3b.addBox(0F, 0F, 0F, 1, 5, 1);
      Shoulder3b.setRotationPoint(-2F, -1F, 7F);
      Shoulder3b.setTextureSize(64, 64);
      Shoulder3b.mirror = true;
      setRotation(Shoulder3b, 0F, 0F, 0F);
      Shoulder3a = new ModelRenderer(this, 41, 28);
      Shoulder3a.addBox(0F, 0F, 0F, 1, 5, 1);
      Shoulder3a.setRotationPoint(8F, -1F, 7F);
      Shoulder3a.setTextureSize(64, 64);
      Shoulder3a.mirror = true;
      setRotation(Shoulder3a, 0F, 0F, 0F);
      Shoulder4b = new ModelRenderer(this, 46, 28);
      Shoulder4b.addBox(0F, 0F, 0F, 1, 4, 1);
      Shoulder4b.setRotationPoint(-2F, 0F, 8F);
      Shoulder4b.setTextureSize(64, 64);
      Shoulder4b.mirror = true;
      setRotation(Shoulder4b, 0F, 0F, 0F);
      Shoulder4a = new ModelRenderer(this, 51, 28);
      Shoulder4a.addBox(0F, 0F, 0F, 1, 4, 1);
      Shoulder4a.setRotationPoint(8F, 0F, 8F);
      Shoulder4a.setTextureSize(64, 64);
      Shoulder4a.mirror = true;
      setRotation(Shoulder4a, 0F, 0F, 0F);
      Arm1 = new ModelRenderer(this, 24, 14);
      Arm1.addBox(0F, 0F, 0F, 14, 3, 3);
      Arm1.setRotationPoint(8F, 2F, 3F);
      Arm1.setTextureSize(64, 64);
      Arm1.mirror = true;
      setRotation(Arm1, 0F, 0F, 0F);
      Arm2 = new ModelRenderer(this, 27, 21);
      Arm2.addBox(-14F, 0F, 0F, 14, 3, 3);
      Arm2.setRotationPoint(-1F, 2F, 3F);
      Arm2.setTextureSize(64, 64);
      Arm2.mirror = true;
      setRotation(Arm2, 0F, 0F, 0F);
      Arm11 = new ModelRenderer(this, 27, 28);
      Arm11.addBox(0F, 0F, 0F, 1, 2, 3);
      Arm11.setRotationPoint(22F, 2F, 3F);
      Arm11.setTextureSize(64, 64);
      Arm11.mirror = true;
      setRotation(Arm11, 0F, 0F, 0F);
      Arm12 = new ModelRenderer(this, 17, 0);
      Arm12.addBox(0F, 0F, 0F, 1, 1, 1);
      Arm12.setRotationPoint(23F, 2F, 4F);
      Arm12.setTextureSize(64, 64);
      Arm12.mirror = true;
      setRotation(Arm12, 0F, 0F, 0F);
      Arm21 = new ModelRenderer(this, 27, 34);
      Arm21.addBox(0F, 0F, 0F, 1, 2, 3);
      Arm21.setRotationPoint(-16F, 2F, 3F);
      Arm21.setTextureSize(64, 64);
      Arm21.mirror = true;
      setRotation(Arm21, 0F, 0F, 0F);
      Arm22 = new ModelRenderer(this, 17, 0);
      Arm22.addBox(0F, 0F, 0F, 1, 1, 1);
      Arm22.setRotationPoint(-17F, 2F, 4F);
      Arm22.setTextureSize(64, 64);
      Arm22.mirror = true;
      setRotation(Arm22, 0F, 0F, 0F);
      Finger13 = new ModelRenderer(this, 23, 0);
      Finger13.addBox(0F, 0F, 0F, 2, 1, 1);
      Finger13.setRotationPoint(21F, 5F, 4F);
      Finger13.setTextureSize(64, 64);
      Finger13.mirror = true;
      setRotation(Finger13, 0F, 0F, 0F);
      Finger23 = new ModelRenderer(this, 23, 0);
      Finger23.addBox(-3F, 0F, 0F, 2, 1, 1);
      Finger23.setRotationPoint(-13F, 5F, 4F);
      Finger23.setTextureSize(64, 64);
      Finger23.mirror = true;
      setRotation(Finger23, 0F, 0F, 0F);
      Finger12 = new ModelRenderer(this, 23, 0);
      Finger12.addBox(0F, 0F, 0F, 1, 2, 1);
      Finger12.setRotationPoint(23F, 3F, 5F);
      Finger12.setTextureSize(64, 64);
      Finger12.mirror = true;
      setRotation(Finger12, 0F, 0F, 0F);
      Finger11 = new ModelRenderer(this, 23, 0);
      Finger11.addBox(0F, 0F, 0F, 1, 2, 1);
      Finger11.setRotationPoint(23F, 3F, 3F);
      Finger11.setTextureSize(64, 64);
      Finger11.mirror = true;
      setRotation(Finger11, 0F, 0F, 0F);
      Finger21 = new ModelRenderer(this, 23, 0);
      Finger21.addBox(0F, 0F, 0F, 1, 2, 1);
      Finger21.setRotationPoint(-17F, 3F, 3F);
      Finger21.setTextureSize(64, 64);
      Finger21.mirror = true;
      setRotation(Finger21, 0F, 0F, 0F);
      Finger22 = new ModelRenderer(this, 23, 0);
      Finger22.addBox(-16F, 3F, 5F, 1, 2, 1);
      Finger22.setRotationPoint(-1F, 0F, 0F);
      Finger22.setTextureSize(64, 64);
      Finger22.mirror = true;
      setRotation(Finger22, 0F, 0F, 0F);
      Grenade1 = new ModelRenderer(this, 31, 51);
      Grenade1.addBox(0F, 0F, 0F, 3, 3, 3);
      Grenade1.setRotationPoint(2F, 2F, 21F);
      Grenade1.setTextureSize(64, 64);
      Grenade1.mirror = true;
      setRotation(Grenade1, 0F, 0F, 0F);
      Grenade2 = new ModelRenderer(this, 44, 51);
      Grenade2.addBox(0F, 0F, 0F, 3, 1, 2);
      Grenade2.setRotationPoint(2F, 3F, 24F);
      Grenade2.setTextureSize(64, 64);
      Grenade2.mirror = true;
      setRotation(Grenade2, 0F, 0F, 0F);
      Grenade3 = new ModelRenderer(this, 44, 55);
      Grenade3.addBox(0F, 0F, 0F, 1, 3, 2);
      Grenade3.setRotationPoint(3F, 2F, 24F);
      Grenade3.setTextureSize(64, 64);
      Grenade3.mirror = true;
      setRotation(Grenade3, 0F, 0F, 0F);
      Greanade4 = new ModelRenderer(this, 56, 0);
      Greanade4.addBox(0F, 0F, 0F, 1, 1, 3);
      Greanade4.setRotationPoint(3F, 5F, 21F);
      Greanade4.setTextureSize(64, 64);
      Greanade4.mirror = true;
      setRotation(Greanade4, 0F, 0F, 0F);
      Grenade5 = new ModelRenderer(this, 56, 0);
      Grenade5.addBox(0F, 0F, 0F, 1, 1, 3);
      Grenade5.setRotationPoint(3F, 1F, 21F);
      Grenade5.setTextureSize(64, 64);
      Grenade5.mirror = true;
      setRotation(Grenade5, 0F, 0F, 0F);
      Grenade6 = new ModelRenderer(this, 56, 0);
      Grenade6.addBox(0F, 0F, 0F, 1, 1, 3);
      Grenade6.setRotationPoint(5F, 3F, 21F);
      Grenade6.setTextureSize(64, 64);
      Grenade6.mirror = true;
      setRotation(Grenade6, 0F, 0F, 0F);
      Grenade7 = new ModelRenderer(this, 56, 0);
      Grenade7.addBox(0F, 0F, 0F, 1, 1, 3);
      Grenade7.setRotationPoint(1F, 3F, 21F);
      Grenade7.setTextureSize(64, 64);
      Grenade7.mirror = true;
      setRotation(Grenade7, 0F, 0F, 0F);
      Body7 = new ModelRenderer(this, 44, 35);
      Body7.addBox(0F, 0F, 0F, 9, 4, 1);
      Body7.setRotationPoint(-1F, 1F, 10F);
      Body7.setTextureSize(64, 64);
      Body7.mirror = true;
      setRotation(Body7, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Face.render(f5);
    Body1.render(f5);
    Body2.render(f5);
    Body3.render(f5);
    Body4.render(f5);
    Body5.render(f5);
    Body6.render(f5);
    Body8.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Belly1.render(f5);
    Belly2.render(f5);
    Shoulder1a.render(f5);
    Shoulder1b.render(f5);
    Shoulder2b.render(f5);
    Shoulder2a.render(f5);
    Shoulder3b.render(f5);
    Shoulder3a.render(f5);
    Shoulder4b.render(f5);
    Shoulder4a.render(f5);
    Arm1.render(f5);
    Arm2.render(f5);
    Arm11.render(f5);
    Arm12.render(f5);
    Arm21.render(f5);
    Arm22.render(f5);
    Finger13.render(f5);
    Finger23.render(f5);
    Finger12.render(f5);
    Finger11.render(f5);
    Finger21.render(f5);
    Finger22.render(f5);
    Grenade1.render(f5);
    Grenade2.render(f5);
    Grenade3.render(f5);
    Greanade4.render(f5);
    Grenade5.render(f5);
    Grenade6.render(f5);
    Grenade7.render(f5);
    Body7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
